# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers

    working_directory: ~/aqapython

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Install allure CLI
          command: |
            uname -a
            sudo npm install -g allure-commandline --save-dev

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            circleci tests glob tests/**/*.py
            python3 -m pytest -n 5 --alluredir ~/aqapython/allure_results

      - run:
          name: report
          command: |
            allure generate -c ~/aqapython/allure_results -o ~/aqapython/allure_reports
          when: always

      - store_artifacts:
          path: ~/aqapython/allure_reports
          destination: allure_reports
          when: always