# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/aqapython

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install allure CLI
          comand: |
            uname -a
            sudo npm install -g allure-comandline --save-dev

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            circleci tests glob tests/**/*.py
            python3 -m pytest --alluredir ~/repo/raw_test_result_json

      - run:
          name: report
          command: |
            allure generate -c ~/repo/raw_test_result_json -o ~/repo/test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports
          when: always